#!/bin/bash

# Hyprland壁紙設定スクリプト
# Usage: ./set-wallpaper.sh [wallpaper-name] [--random]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(dirname "$SCRIPT_DIR")"
WALLPAPER_DIR="$DOTFILES_DIR/wallpaper"
HYPRPAPER_CONF="$DOTFILES_DIR/.config/hypr/hyprpaper.conf"

# 色定義
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# モニター情報を取得
get_monitors() {
    hyprctl monitors -j | grep -oP '"name":"\K[^"]+' || echo "DP-2 HDMI-A-1"
}

# 壁紙リストを取得
list_wallpapers() {
    find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) -exec basename {} \;
}

# ランダムに壁紙を選択
random_wallpaper() {
    list_wallpapers | shuf -n 1
}

# 対話的に壁紙を選択
select_wallpaper() {
    echo -e "${BLUE}利用可能な壁紙:${NC}"
    echo ""

    local wallpapers=($(list_wallpapers))
    local i=1

    for wp in "${wallpapers[@]}"; do
        echo "  $i) $wp"
        ((i++))
    done

    echo ""
    read -p "壁紙を選択してください [1-${#wallpapers[@]}]: " selection

    if [[ "$selection" =~ ^[0-9]+$ ]] && [ "$selection" -ge 1 ] && [ "$selection" -le "${#wallpapers[@]}" ]; then
        echo "${wallpapers[$((selection-1))]}"
    else
        echo ""
        return 1
    fi
}

# hyprpaper.confを生成
generate_hyprpaper_conf() {
    local wallpaper_path="$1"
    local monitors=($(get_monitors))

    cat > "$HYPRPAPER_CONF" << EOF
# Hyprpaper configuration
# Generated by set-wallpaper.sh

preload = $wallpaper_path

EOF

    # 各モニターに壁紙を設定
    for monitor in "${monitors[@]}"; do
        echo "wallpaper = $monitor,$wallpaper_path" >> "$HYPRPAPER_CONF"
    done

    # スプラッシュスクリーンを無効化
    echo "" >> "$HYPRPAPER_CONF"
    echo "splash = false" >> "$HYPRPAPER_CONF"
}

# hyprpaperをリロード
reload_hyprpaper() {
    if pgrep -x hyprpaper > /dev/null; then
        killall hyprpaper
        sleep 0.5
    fi

    hyprpaper &
    disown
}

# メイン処理
main() {
    local wallpaper_name=""

    # 引数を解析
    if [ "$1" == "--random" ] || [ "$1" == "-r" ]; then
        wallpaper_name=$(random_wallpaper)
        echo -e "${YELLOW}→${NC} ランダム選択: $wallpaper_name"
    elif [ -n "$1" ]; then
        wallpaper_name="$1"
    else
        wallpaper_name=$(select_wallpaper)
        if [ $? -ne 0 ]; then
            echo "壁紙の選択がキャンセルされました"
            exit 1
        fi
    fi

    # 壁紙ファイルの存在確認
    local wallpaper_path="$WALLPAPER_DIR/$wallpaper_name"
    if [ ! -f "$wallpaper_path" ]; then
        echo -e "${YELLOW}エラー:${NC} 壁紙が見つかりません: $wallpaper_name"
        echo ""
        echo "利用可能な壁紙:"
        list_wallpapers | sed 's/^/  - /'
        exit 1
    fi

    echo ""
    echo -e "${GREEN}→${NC} 壁紙を設定中: $wallpaper_name"

    # hyprpaper.confを生成
    generate_hyprpaper_conf "$wallpaper_path"
    echo -e "${GREEN}✓${NC} 設定ファイル更新: $HYPRPAPER_CONF"

    # hyprpaperをリロード
    reload_hyprpaper
    echo -e "${GREEN}✓${NC} hyprpaperをリロード"

    echo ""
    echo -e "${GREEN}完了!${NC} 壁紙が設定されました"
    echo ""
    echo "適用されたモニター:"
    get_monitors | sed 's/^/  - /'
}

# 引数チェック
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo "Usage: $0 [wallpaper-name] [--random]"
    echo ""
    echo "Options:"
    echo "  wallpaper-name    壁紙ファイル名を指定"
    echo "  -r, --random      ランダムに壁紙を選択"
    echo "  -h, --help        このヘルプを表示"
    echo ""
    echo "引数なしで実行すると対話的に選択できます"
    echo ""
    echo "Examples:"
    echo "  $0                        # 対話的に選択"
    echo "  $0 wallpaper.jpg          # 指定した壁紙を設定"
    echo "  $0 --random               # ランダムに選択"
    exit 0
fi

main "$@"
